//require('./exercice/exercice');
//require('./05-tableaux/maintab');
//require('./06-string/main');
//require('./07-object-function/main');
//require('./exercice/part1');
//require('./exercice/part2');
// require('./08-complement/notion-de-class');
// require('./08-complement/complement-de-fonction');
//require('./exercice/partie3');
//require('./exercice/partie4');
require('./10-les-objets-du-BOM/04-naviguer-dans-le-DOM/main');
